before_install:
  - sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update

install:
  - sudo apt-get install biber
  - apt-cache search biber
  - apt-cache search tex

script:
  - pdflatex --version
  - makeindex --version
  - which biber
  - biber --help
